return {
  'nvim-treesitter/nvim-treesitter',
  opts = {
    ensure_installed = {
      'bash',
      'c',
      'cpp',
      'css',
      'git_config',
      'git_rebase',
      'gitattributes',
      'gitcommit',
      'gitignore',
      'go',
      'lua',
      'markdown',
      'markdown_inline',
      'python',
      'query',
      'ruby',
      'rust',
      'ssh_config',
      'sql',
      'tsx',
      'javascript',
      'typescript',
      'vimdoc',
      'vim',
      'vue',
      'xml',
      'yaml',
    },
  },
}
